name: Auto Deploy after push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [16.17.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: cd client && npm install

      - name: Build
        run:  cd client && CI='false' npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.arn:aws:s3:::wacatbucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.test_user }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.rhtmaehf2@ }}
          AWS_REGION: ${{ secrets.ap-northeast-2 }}
          SOURCE_DIR: "dist"